pdf_file_path: /Jingzhan_Lu-CV-Exeter.pdf
[Open PDF]({{ site.pdf_file_path }}){:target="_blank" onclick="ga('send', 'event', 'Download', 'PDF', 'Jingzhan_Lu-CV-Exeter.pdf');"}
google_analytics:
theme: jekyll-theme-cayman
